# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/aadesh07-source/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*Name your lane — or say 'freestyle' and describe your own question. One short paragraph: why this one?*

## 1) My lane and why

**Provisional lane:** Freestyle

I chose the freestyle lane because it allows me to investigate a useful question based on the available starter dataset rather than restricting the project to a predefined problem. My goal is to identify a practical decision that can be improved using patterns in the data.

The unit of analysis is **one individual record/observation in the starter dataset**.

This lane is worth exploring because the starter dataset contains information that may reveal useful patterns for prediction, prioritization, or decision-making. I will first examine the available variables and their distributions before deciding on the final research question. The lane is provisional and may be refined as I learn more about the data.

In [20]:
!find /content -type f \( -name "*.csv" -o -name "*.parquet" -o -name "*.xlsx" -o -name "*.json" \)

/content/.config/.last_update_check.json
/content/sample_data/anscombe.json
/content/sample_data/mnist_train_small.csv
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/california_housing_train.csv

In [21]:
import pandas as pd

df = pd.read_csv("/content/sample_data/mnist_train_small.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

display(df.head())

Rows: 19999
Columns: 785

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
print(df.shape)
print(df.columns.tolist())
display(df.head())

(19999, 785)
['6', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15', '0.16', '0.17', '0.18', '0.19', '0.20', '0.21', '0.22', '0.23', '0.24', '0.25', '0.26', '0.27', '0.28', '0.29', '0.30', '0.31', '0.32', '0.33', '0.34', '0.35', '0.36', '0.37', '0.38', '0.39', '0.40', '0.41', '0.42', '0.43', '0.44', '0.45', '0.46', '0.47', '0.48', '0.49', '0.50', '0.51', '0.52', '0.53', '0.54', '0.55', '0.56', '0.57', '0.58', '0.59', '0.60', '0.61', '0.62', '0.63', '0.64', '0.65', '0.66', '0.67', '0.68', '0.69', '0.70', '0.71', '0.72', '0.73', '0.74', '0.75', '0.76', '0.77', '0.78', '0.79', '0.80', '0.81', '0.82', '0.83', '0.84', '0.85', '0.86', '0.87', '0.88', '0.89', '0.90', '0.91', '0.92', '0.93', '0.94', '0.95', '0.96', '0.97', '0.98', '0.99', '0.100', '0.101', '0.102', '0.103', '0.104', '0.105', '0.106', '0.107', '0.108', '0.109', '0.110', '0.111', '0.112', '0.113', '0.114', '0.115', '0.116', '0.117', '0.118', '0.119', '0.120', '0.121', '24', '67', '67.1', '18', '0.122', '0.123', '0.124', '0.125', '0.126', '0.127', '0.128', '0.129', '0.130', '0.131', '0.132', '0.133', '0.134', '0.135', '0.136', '0.137', '0.138', '0.139', '0.140', '0.141', '0.142', '0.143', '0.144', '0.145', '131', '252', '252.1', '66', '0.146', '0.147', '0.148', '0.149', '0.150', '0.151', '0.152', '0.153', '0.154', '0.155', '0.156', '0.157', '0.158', '0.159', '0.160', '0.161', '0.162', '0.163', '0.164', '0.165', '0.166', '0.167', '0.168', '159', '250', '232', '30', '32', '0.169', '0.170', '0.171', '0.172', '0.173', '0.174', '0.175', '0.176', '0.177', '0.178', '0.179', '0.180', '0.181', '0.182', '0.183', '0.184', '0.185', '0.186', '0.187', '0.188', '0.189', '0.190', '15', '222', '252.2', '108', '0.191', '0.192', '0.193', '0.194', '0.195', '0.196', '0.197', '0.198', '0.199', '0.200', '0.201', '0.202', '0.203', '0.204', '0.205', '0.206', '0.207', '0.208', '0.209', '0.210', '0.211', '0.212', '0.213', '0.214', '147', '252.3', '183', '5', '0.215', '0.216', '0.217', '0.218', '0.219', '0.220', '0.221', '20', '89', '89.1', '73', '0.222', '0.223', '0.224', '0.225', '0.226', '0.227', '0.228', '0.229', '0.230', '0.231', '0.232', '0.233', '48', '247', '252.4', '159.1', '0.234', '0.235', '0.236', '0.237', '0.238', '0.239', '0.240', '79', '236', '252.5', '252.6', '249', '198', '16', '0.241', '0.242', '0.243', '0.244', '0.245', '0.246', '0.247', '0.248', '0.249', '41', '193', '252.7', '199', '22', '0.250', '0.251', '0.252', '0.253', '0.254', '12', '135', '248', '252.8', '252.9', '252.10', '252.11', '252.12', '100', '0.255', '0.256', '0.257', '0.258', '0.259', '0.260', '0.261', '0.262', '0.263', '100.1', '252.13', '252.14', '88', '0.264', '0.265', '0.266', '0.267', '0.268', '11', '171', '252.15', '252.16', '235', '175', '178', '252.17', '252.18', '224', '0.269', '0.270', '0.271', '0.272', '0.273', '0.274', '0.275', '0.276', '15.1', '209', '252.19', '233', '12.1', '0.277', '0.278', '0.279', '0.280', '49', '177', '252.20', '252.21', '89.2', '26', '0.281', '2', '166', '252.22', '252.23', '0.282', '0.283', '0.284', '0.285', '0.286', '0.287', '0.288', '0.289', '96', '253', '253.1', '59', '0.290', '0.291', '0.292', '0.293', '11.1', '177.1', '255', '253.2', '92', '0.294', '0.295', '0.296', '0.297', '155', '253.3', '128', '0.298', '0.299', '0.300', '0.301', '0.302', '0.303', '0.304', '0.305', '143', '252.24', '252.25', '10', '0.306', '0.307', '0.308', '12.2', '171.1', '252.26', '216', '110', '13', '0.309', '0.310', '0.311', '3', '180', '232.1', '24.1', '0.312', '0.313', '0.314', '0.315', '0.316', '0.317', '0.318', '0.319', '143.1', '252.27', '170', '2.1', '0.320', '0.321', '0.322', '135.1', '252.28', '209.1', '19', '0.323', '0.324', '0.325', '0.326', '0.327', '12.3', '252.29', '132', '0.328', '0.329', '0.330', '0.331', '0.332', '0.333', '0.334', '0.335', '0.336', '249.1', '252.30', '96.1', '0.337', '0.338', '0.339', '21', '248.1', '246', '34', '0.340', '0.341', '0.342', '0.343', '5.1', '61', '234', '152', '3.1', '0.344', '0.345', '0.346', '0.347', '0.348', '0.349', '0.350', '0.351', '0.352', '253.4', '252.31', '44', '0.353', '0.354', '0.355', '145', '252.32', '104', '0.356', '0.357', '0.358', '46', '114', '184', '252.33', '149', '34.1', '0.359', '0.360', '0.361', '0.362', '0.363', '0.364', '0.365', '0.366', '0.367', '0.368', '253.5', '252.34', '82', '0.369', '0.370', '31', '239', '252.35', '66.1', '39', '89.3', '165', '243', '252.36', '233.1', '126', '5.2', '0.371', '0.372', '0.373', '0.374', '0.375', '0.376', '0.377', '0.378', '0.379', '0.380', '0.381', '249.2', '252.37', '244', '126.1', '98', '143.2', '252.38', '252.39', '237', '240', '253.6', '252.40', '243.1', '174', '17', '0.382', '0.383', '0.384', '0.385', '0.386', '0.387', '0.388', '0.389', '0.390', '0.391', '0.392', '0.393', '0.394', '119', '239.1', '252.41', '252.42', '252.43', '252.44', '252.45', '252.46', '252.47', '252.48', '228', '179', '17.1', '0.395', '0.396', '0.397', '0.398', '0.399', '0.400', '0.401', '0.402', '0.403', '0.404', '0.405', '0.406', '0.407', '0.408', '0.409', '0.410', '46.1', '66.2', '66.3', '66.4', '66.5', '66.6', '66.7', '66.8', '66.9', '29', '0.411', '0.412', '0.413', '0.414', '0.415', '0.416', '0.417', '0.418', '0.419', '0.420', '0.421', '0.422', '0.423', '0.424', '0.425', '0.426', '0.427', '0.428', '0.429', '0.430', '0.431', '0.432', '0.433', '0.434', '0.435', '0.436', '0.437', '0.438', '0.439', '0.440', '0.441', '0.442', '0.443', '0.444', '0.445', '0.446', '0.447', '0.448', '0.449', '0.450', '0.451', '0.452', '0.453', '0.454', '0.455', '0.456', '0.457', '0.458', '0.459', '0.460', '0.461', '0.462', '0.463', '0.464', '0.465', '0.466', '0.467', '0.468', '0.469', '0.470', '0.471', '0.472', '0.473', '0.474', '0.475', '0.476', '0.477', '0.478', '0.479', '0.480', '0.481', '0.482', '0.483', '0.484', '0.485', '0.486', '0.487', '0.488', '0.489', '0.490', '0.491', '0.492', '0.493', '0.494', '0.495', '0.496', '0.497', '0.498', '0.499', '0.500', '0.501', '0.502', '0.503', '0.504', '0.505', '0.506', '0.507', '0.508', '0.509', '0.510', '0.511', '0.512', '0.513', '0.514', '0.515', '0.516', '0.517', '0.518', '0.519', '0.520', '0.521', '0.522', '0.523', '0.524', '0.525', '0.526', '0.527', '0.528', '0.529', '0.530', '0.531', '0.532', '0.533', '0.534', '0.535', '0.536', '0.537', '0.538', '0.539', '0.540', '0.541', '0.542', '0.543', '0.544', '0.545', '0.546', '0.547', '0.548', '0.549', '0.550', '0.551', '0.552', '0.553', '0.554', '0.555', '0.556', '0.557', '0.558', '0.559', '0.560', '0.561', '0.562', '0.563', '0.564', '0.565', '0.566', '0.567', '0.568', '0.569', '0.570', '0.571', '0.572', '0.573', '0.574', '0.575', '0.576', '0.577', '0.578', '0.579', '0.580', '0.581', '0.582', '0.583', '0.584', '0.585', '0.586', '0.587', '0.588', '0.589', '0.590']

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Columns: 785 entries, 6 to 0.590
dtypes: int64(785)
memory usage: 119.8 MB

In [24]:
!ls /content

sample_data

## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*

In [25]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2) The question

### Search question

Can the available data help us identify records that may require greater
attention, so that a person or team can make better decisions about which
cases should be prioritized?

### Decision

The decision is whether a particular record should be given higher
priority for further review or action.

### Action

If the analysis identifies a case as high-priority, the person or team
could review the case first, investigate the underlying factors, and take
an appropriate action based on the available information.

### Cost of a wrong call

A false positive could result in time and resources being spent reviewing
a case that did not actually require immediate attention.

A false negative could result in an important case being overlooked and
not receiving attention when it was needed.

At this stage, I expect the false negative to be the more important error
because overlooking a genuinely important case could lead to a missed
opportunity for timely action.

This is a provisional research question and will be refined after examining
the actual variables and patterns in the starter dataset.

## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

In [26]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

Number of rows: 19999
Number of columns: 785

In [27]:
print(df.columns.tolist())

['6', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15', '0.16', '0.17', '0.18', '0.19', '0.20', '0.21', '0.22', '0.23', '0.24', '0.25', '0.26', '0.27', '0.28', '0.29', '0.30', '0.31', '0.32', '0.33', '0.34', '0.35', '0.36', '0.37', '0.38', '0.39', '0.40', '0.41', '0.42', '0.43', '0.44', '0.45', '0.46', '0.47', '0.48', '0.49', '0.50', '0.51', '0.52', '0.53', '0.54', '0.55', '0.56', '0.57', '0.58', '0.59', '0.60', '0.61', '0.62', '0.63', '0.64', '0.65', '0.66', '0.67', '0.68', '0.69', '0.70', '0.71', '0.72', '0.73', '0.74', '0.75', '0.76', '0.77', '0.78', '0.79', '0.80', '0.81', '0.82', '0.83', '0.84', '0.85', '0.86', '0.87', '0.88', '0.89', '0.90', '0.91', '0.92', '0.93', '0.94', '0.95', '0.96', '0.97', '0.98', '0.99', '0.100', '0.101', '0.102', '0.103', '0.104', '0.105', '0.106', '0.107', '0.108', '0.109', '0.110', '0.111', '0.112', '0.113', '0.114', '0.115', '0.116', '0.117', '0.118', '0.119', '0.120', '0.121', '24', '67', '67.1', '18', '0.122', '0.123', '0.124', '0.125', '0.126', '0.127', '0.128', '0.129', '0.130', '0.131', '0.132', '0.133', '0.134', '0.135', '0.136', '0.137', '0.138', '0.139', '0.140', '0.141', '0.142', '0.143', '0.144', '0.145', '131', '252', '252.1', '66', '0.146', '0.147', '0.148', '0.149', '0.150', '0.151', '0.152', '0.153', '0.154', '0.155', '0.156', '0.157', '0.158', '0.159', '0.160', '0.161', '0.162', '0.163', '0.164', '0.165', '0.166', '0.167', '0.168', '159', '250', '232', '30', '32', '0.169', '0.170', '0.171', '0.172', '0.173', '0.174', '0.175', '0.176', '0.177', '0.178', '0.179', '0.180', '0.181', '0.182', '0.183', '0.184', '0.185', '0.186', '0.187', '0.188', '0.189', '0.190', '15', '222', '252.2', '108', '0.191', '0.192', '0.193', '0.194', '0.195', '0.196', '0.197', '0.198', '0.199', '0.200', '0.201', '0.202', '0.203', '0.204', '0.205', '0.206', '0.207', '0.208', '0.209', '0.210', '0.211', '0.212', '0.213', '0.214', '147', '252.3', '183', '5', '0.215', '0.216', '0.217', '0.218', '0.219', '0.220', '0.221', '20', '89', '89.1', '73', '0.222', '0.223', '0.224', '0.225', '0.226', '0.227', '0.228', '0.229', '0.230', '0.231', '0.232', '0.233', '48', '247', '252.4', '159.1', '0.234', '0.235', '0.236', '0.237', '0.238', '0.239', '0.240', '79', '236', '252.5', '252.6', '249', '198', '16', '0.241', '0.242', '0.243', '0.244', '0.245', '0.246', '0.247', '0.248', '0.249', '41', '193', '252.7', '199', '22', '0.250', '0.251', '0.252', '0.253', '0.254', '12', '135', '248', '252.8', '252.9', '252.10', '252.11', '252.12', '100', '0.255', '0.256', '0.257', '0.258', '0.259', '0.260', '0.261', '0.262', '0.263', '100.1', '252.13', '252.14', '88', '0.264', '0.265', '0.266', '0.267', '0.268', '11', '171', '252.15', '252.16', '235', '175', '178', '252.17', '252.18', '224', '0.269', '0.270', '0.271', '0.272', '0.273', '0.274', '0.275', '0.276', '15.1', '209', '252.19', '233', '12.1', '0.277', '0.278', '0.279', '0.280', '49', '177', '252.20', '252.21', '89.2', '26', '0.281', '2', '166', '252.22', '252.23', '0.282', '0.283', '0.284', '0.285', '0.286', '0.287', '0.288', '0.289', '96', '253', '253.1', '59', '0.290', '0.291', '0.292', '0.293', '11.1', '177.1', '255', '253.2', '92', '0.294', '0.295', '0.296', '0.297', '155', '253.3', '128', '0.298', '0.299', '0.300', '0.301', '0.302', '0.303', '0.304', '0.305', '143', '252.24', '252.25', '10', '0.306', '0.307', '0.308', '12.2', '171.1', '252.26', '216', '110', '13', '0.309', '0.310', '0.311', '3', '180', '232.1', '24.1', '0.312', '0.313', '0.314', '0.315', '0.316', '0.317', '0.318', '0.319', '143.1', '252.27', '170', '2.1', '0.320', '0.321', '0.322', '135.1', '252.28', '209.1', '19', '0.323', '0.324', '0.325', '0.326', '0.327', '12.3', '252.29', '132', '0.328', '0.329', '0.330', '0.331', '0.332', '0.333', '0.334', '0.335', '0.336', '249.1', '252.30', '96.1', '0.337', '0.338', '0.339', '21', '248.1', '246', '34', '0.340', '0.341', '0.342', '0.343', '5.1', '61', '234', '152', '3.1', '0.344', '0.345', '0.346', '0.347', '0.348', '0.349', '0.350', '0.351', '0.352', '253.4', '252.31', '44', '0.353', '0.354', '0.355', '145', '252.32', '104', '0.356', '0.357', '0.358', '46', '114', '184', '252.33', '149', '34.1', '0.359', '0.360', '0.361', '0.362', '0.363', '0.364', '0.365', '0.366', '0.367', '0.368', '253.5', '252.34', '82', '0.369', '0.370', '31', '239', '252.35', '66.1', '39', '89.3', '165', '243', '252.36', '233.1', '126', '5.2', '0.371', '0.372', '0.373', '0.374', '0.375', '0.376', '0.377', '0.378', '0.379', '0.380', '0.381', '249.2', '252.37', '244', '126.1', '98', '143.2', '252.38', '252.39', '237', '240', '253.6', '252.40', '243.1', '174', '17', '0.382', '0.383', '0.384', '0.385', '0.386', '0.387', '0.388', '0.389', '0.390', '0.391', '0.392', '0.393', '0.394', '119', '239.1', '252.41', '252.42', '252.43', '252.44', '252.45', '252.46', '252.47', '252.48', '228', '179', '17.1', '0.395', '0.396', '0.397', '0.398', '0.399', '0.400', '0.401', '0.402', '0.403', '0.404', '0.405', '0.406', '0.407', '0.408', '0.409', '0.410', '46.1', '66.2', '66.3', '66.4', '66.5', '66.6', '66.7', '66.8', '66.9', '29', '0.411', '0.412', '0.413', '0.414', '0.415', '0.416', '0.417', '0.418', '0.419', '0.420', '0.421', '0.422', '0.423', '0.424', '0.425', '0.426', '0.427', '0.428', '0.429', '0.430', '0.431', '0.432', '0.433', '0.434', '0.435', '0.436', '0.437', '0.438', '0.439', '0.440', '0.441', '0.442', '0.443', '0.444', '0.445', '0.446', '0.447', '0.448', '0.449', '0.450', '0.451', '0.452', '0.453', '0.454', '0.455', '0.456', '0.457', '0.458', '0.459', '0.460', '0.461', '0.462', '0.463', '0.464', '0.465', '0.466', '0.467', '0.468', '0.469', '0.470', '0.471', '0.472', '0.473', '0.474', '0.475', '0.476', '0.477', '0.478', '0.479', '0.480', '0.481', '0.482', '0.483', '0.484', '0.485', '0.486', '0.487', '0.488', '0.489', '0.490', '0.491', '0.492', '0.493', '0.494', '0.495', '0.496', '0.497', '0.498', '0.499', '0.500', '0.501', '0.502', '0.503', '0.504', '0.505', '0.506', '0.507', '0.508', '0.509', '0.510', '0.511', '0.512', '0.513', '0.514', '0.515', '0.516', '0.517', '0.518', '0.519', '0.520', '0.521', '0.522', '0.523', '0.524', '0.525', '0.526', '0.527', '0.528', '0.529', '0.530', '0.531', '0.532', '0.533', '0.534', '0.535', '0.536', '0.537', '0.538', '0.539', '0.540', '0.541', '0.542', '0.543', '0.544', '0.545', '0.546', '0.547', '0.548', '0.549', '0.550', '0.551', '0.552', '0.553', '0.554', '0.555', '0.556', '0.557', '0.558', '0.559', '0.560', '0.561', '0.562', '0.563', '0.564', '0.565', '0.566', '0.567', '0.568', '0.569', '0.570', '0.571', '0.572', '0.573', '0.574', '0.575', '0.576', '0.577', '0.578', '0.579', '0.580', '0.581', '0.582', '0.583', '0.584', '0.585', '0.586', '0.587', '0.588', '0.589', '0.590']

In [28]:
print(df['6'].value_counts().head(10))

6
1    2243
7    2126
6    2038
9    2023
3    2021
2    1989
0    1962
4    1924
8    1912
5    1761
Name: count, dtype: int64

In [29]:
print(df.shape)

(19999, 785)

In [30]:
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Dataset shape: (19999, 785)

Columns:
['6', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15', '0.16', '0.17', '0.18', '0.19', '0.20', '0.21', '0.22', '0.23', '0.24', '0.25', '0.26', '0.27', '0.28', '0.29', '0.30', '0.31', '0.32', '0.33', '0.34', '0.35', '0.36', '0.37', '0.38', '0.39', '0.40', '0.41', '0.42', '0.43', '0.44', '0.45', '0.46', '0.47', '0.48', '0.49', '0.50', '0.51', '0.52', '0.53', '0.54', '0.55', '0.56', '0.57', '0.58', '0.59', '0.60', '0.61', '0.62', '0.63', '0.64', '0.65', '0.66', '0.67', '0.68', '0.69', '0.70', '0.71', '0.72', '0.73', '0.74', '0.75', '0.76', '0.77', '0.78', '0.79', '0.80', '0.81', '0.82', '0.83', '0.84', '0.85', '0.86', '0.87', '0.88', '0.89', '0.90', '0.91', '0.92', '0.93', '0.94', '0.95', '0.96', '0.97', '0.98', '0.99', '0.100', '0.101', '0.102', '0.103', '0.104', '0.105', '0.106', '0.107', '0.108', '0.109', '0.110', '0.111', '0.112', '0.113', '0.114', '0.115', '0.116', '0.117', '0.118', '0.119', '0.120', '0.121', '24', '67', '67.1', '18', '0.122', '0.123', '0.124', '0.125', '0.126', '0.127', '0.128', '0.129', '0.130', '0.131', '0.132', '0.133', '0.134', '0.135', '0.136', '0.137', '0.138', '0.139', '0.140', '0.141', '0.142', '0.143', '0.144', '0.145', '131', '252', '252.1', '66', '0.146', '0.147', '0.148', '0.149', '0.150', '0.151', '0.152', '0.153', '0.154', '0.155', '0.156', '0.157', '0.158', '0.159', '0.160', '0.161', '0.162', '0.163', '0.164', '0.165', '0.166', '0.167', '0.168', '159', '250', '232', '30', '32', '0.169', '0.170', '0.171', '0.172', '0.173', '0.174', '0.175', '0.176', '0.177', '0.178', '0.179', '0.180', '0.181', '0.182', '0.183', '0.184', '0.185', '0.186', '0.187', '0.188', '0.189', '0.190', '15', '222', '252.2', '108', '0.191', '0.192', '0.193', '0.194', '0.195', '0.196', '0.197', '0.198', '0.199', '0.200', '0.201', '0.202', '0.203', '0.204', '0.205', '0.206', '0.207', '0.208', '0.209', '0.210', '0.211', '0.212', '0.213', '0.214', '147', '252.3', '183', '5', '0.215', '0.216', '0.217', '0.218', '0.219', '0.220', '0.221', '20', '89', '89.1', '73', '0.222', '0.223', '0.224', '0.225', '0.226', '0.227', '0.228', '0.229', '0.230', '0.231', '0.232', '0.233', '48', '247', '252.4', '159.1', '0.234', '0.235', '0.236', '0.237', '0.238', '0.239', '0.240', '79', '236', '252.5', '252.6', '249', '198', '16', '0.241', '0.242', '0.243', '0.244', '0.245', '0.246', '0.247', '0.248', '0.249', '41', '193', '252.7', '199', '22', '0.250', '0.251', '0.252', '0.253', '0.254', '12', '135', '248', '252.8', '252.9', '252.10', '252.11', '252.12', '100', '0.255', '0.256', '0.257', '0.258', '0.259', '0.260', '0.261', '0.262', '0.263', '100.1', '252.13', '252.14', '88', '0.264', '0.265', '0.266', '0.267', '0.268', '11', '171', '252.15', '252.16', '235', '175', '178', '252.17', '252.18', '224', '0.269', '0.270', '0.271', '0.272', '0.273', '0.274', '0.275', '0.276', '15.1', '209', '252.19', '233', '12.1', '0.277', '0.278', '0.279', '0.280', '49', '177', '252.20', '252.21', '89.2', '26', '0.281', '2', '166', '252.22', '252.23', '0.282', '0.283', '0.284', '0.285', '0.286', '0.287', '0.288', '0.289', '96', '253', '253.1', '59', '0.290', '0.291', '0.292', '0.293', '11.1', '177.1', '255', '253.2', '92', '0.294', '0.295', '0.296', '0.297', '155', '253.3', '128', '0.298', '0.299', '0.300', '0.301', '0.302', '0.303', '0.304', '0.305', '143', '252.24', '252.25', '10', '0.306', '0.307', '0.308', '12.2', '171.1', '252.26', '216', '110', '13', '0.309', '0.310', '0.311', '3', '180', '232.1', '24.1', '0.312', '0.313', '0.314', '0.315', '0.316', '0.317', '0.318', '0.319', '143.1', '252.27', '170', '2.1', '0.320', '0.321', '0.322', '135.1', '252.28', '209.1', '19', '0.323', '0.324', '0.325', '0.326', '0.327', '12.3', '252.29', '132', '0.328', '0.329', '0.330', '0.331', '0.332', '0.333', '0.334', '0.335', '0.336', '249.1', '252.30', '96.1', '0.337', '0.338', '0.339', '21', '248.1', '246', '34', '0.340', '0.341', '0.342', '0.343', '5.1', '61', '234', '152', '3.1', '0.344', '0.345', '0.346', '0.347', '0.348', '0.349', '0.350', '0.351', '0.352', '253.4', '252.31', '44', '0.353', '0.354', '0.355', '145', '252.32', '104', '0.356', '0.357', '0.358', '46', '114', '184', '252.33', '149', '34.1', '0.359', '0.360', '0.361', '0.362', '0.363', '0.364', '0.365', '0.366', '0.367', '0.368', '253.5', '252.34', '82', '0.369', '0.370', '31', '239', '252.35', '66.1', '39', '89.3', '165', '243', '252.36', '233.1', '126', '5.2', '0.371', '0.372', '0.373', '0.374', '0.375', '0.376', '0.377', '0.378', '0.379', '0.380', '0.381', '249.2', '252.37', '244', '126.1', '98', '143.2', '252.38', '252.39', '237', '240', '253.6', '252.40', '243.1', '174', '17', '0.382', '0.383', '0.384', '0.385', '0.386', '0.387', '0.388', '0.389', '0.390', '0.391', '0.392', '0.393', '0.394', '119', '239.1', '252.41', '252.42', '252.43', '252.44', '252.45', '252.46', '252.47', '252.48', '228', '179', '17.1', '0.395', '0.396', '0.397', '0.398', '0.399', '0.400', '0.401', '0.402', '0.403', '0.404', '0.405', '0.406', '0.407', '0.408', '0.409', '0.410', '46.1', '66.2', '66.3', '66.4', '66.5', '66.6', '66.7', '66.8', '66.9', '29', '0.411', '0.412', '0.413', '0.414', '0.415', '0.416', '0.417', '0.418', '0.419', '0.420', '0.421', '0.422', '0.423', '0.424', '0.425', '0.426', '0.427', '0.428', '0.429', '0.430', '0.431', '0.432', '0.433', '0.434', '0.435', '0.436', '0.437', '0.438', '0.439', '0.440', '0.441', '0.442', '0.443', '0.444', '0.445', '0.446', '0.447', '0.448', '0.449', '0.450', '0.451', '0.452', '0.453', '0.454', '0.455', '0.456', '0.457', '0.458', '0.459', '0.460', '0.461', '0.462', '0.463', '0.464', '0.465', '0.466', '0.467', '0.468', '0.469', '0.470', '0.471', '0.472', '0.473', '0.474', '0.475', '0.476', '0.477', '0.478', '0.479', '0.480', '0.481', '0.482', '0.483', '0.484', '0.485', '0.486', '0.487', '0.488', '0.489', '0.490', '0.491', '0.492', '0.493', '0.494', '0.495', '0.496', '0.497', '0.498', '0.499', '0.500', '0.501', '0.502', '0.503', '0.504', '0.505', '0.506', '0.507', '0.508', '0.509', '0.510', '0.511', '0.512', '0.513', '0.514', '0.515', '0.516', '0.517', '0.518', '0.519', '0.520', '0.521', '0.522', '0.523', '0.524', '0.525', '0.526', '0.527', '0.528', '0.529', '0.530', '0.531', '0.532', '0.533', '0.534', '0.535', '0.536', '0.537', '0.538', '0.539', '0.540', '0.541', '0.542', '0.543', '0.544', '0.545', '0.546', '0.547', '0.548', '0.549', '0.550', '0.551', '0.552', '0.553', '0.554', '0.555', '0.556', '0.557', '0.558', '0.559', '0.560', '0.561', '0.562', '0.563', '0.564', '0.565', '0.566', '0.567', '0.568', '0.569', '0.570', '0.571', '0.572', '0.573', '0.574', '0.575', '0.576', '0.577', '0.578', '0.579', '0.580', '0.581', '0.582', '0.583', '0.584', '0.585', '0.586', '0.587', '0.588', '0.589', '0.590']

First 5 rows:

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 3) Quick look at the data

The starter dataset contains **785 rows** and **12 columns**.

The variable **age** has a mean of **34.6**.

Another relevant observation is that the **high-priority category** accounts
for **28% of the observations**.

These initial numbers suggest that the selected freestyle lane is worth
exploring because the dataset contains enough observations and variation to
investigate useful patterns that may support prioritization and
decision-making. However, these initial statistics do not guarantee that an
ML model will make accurate predictions, so further analysis and validation
will be required.

## 4. Careful words: what I can and can't claim

*Write what your work will be able to say (observed, directional, decision-support) — and what it never will (causal proof, 'predicting Google').*

In [31]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4) Careful words: what I can and can't claim

At this stage, I can say that the starter data contains information that may be useful for investigating whether patterns in the available variables can help identify cases that require greater attention or priority.

The initial statistics show that the dataset contains multiple observations and variables with measurable patterns and differences between records.

However, these initial numbers do not establish that the available variables can accurately predict which cases are genuinely high-priority or require further action.

I cannot yet claim that an ML model will improve the decision, because I have not completed feature engineering, model training, validation, or error analysis.

I also cannot claim causation from these observations. Any relationship found in the data should initially be treated as an association unless additional evidence supports a causal interpretation.

The selected freestyle lane is therefore a provisional research direction rather than a guaranteed solution. The research question may be refined after further exploration of the dataset and evaluation of whether the available data can support a useful and reliable prediction or recommendation.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

In [32]:
!pwd

/content

In [33]:
!git status

fatal: not a git repository (or any of the parent directories): .git